# Generated by Django 3.2.15 on 2022-09-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_availability_availabilityoccurrence_classroomreservation_timeslot'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, help_text='The field will be filled in automatically after saving', null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_duration',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], help_text='hour(s)', null=True, verbose_name='Lesson duration'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='comment',
            field=models.ManyToManyField(blank=True, default=None, to='course.Comment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.classroom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='all_course_dates',
            field=models.CharField(blank=True, default='', help_text='The field will be filled in automatically after saving', max_length=200, verbose_name='All course days'),
        ),
        migrations.AlterField(
            model_name='course',
            name='choices',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Start time options'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, default='', help_text='The field will be filled in automatically after saving', max_length=16, verbose_name='Course type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.classroom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_day_of_week',
            field=models.CharField(blank=True, default='', help_text='The field will be filled in automatically after saving', max_length=200, verbose_name='Start day of week'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=9, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=9, verbose_name='Start time'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('start_date', 'location', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('location', 'date', 'start_time')},
        ),
    ]
