# Generated by Django 4.1 on 2022-09-02 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_middle_name', message='Invalid middle name', regex='^[А-яа-я-\\s]{1,50}$')], verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Invalid name', regex='^[А-яа-я-\\s]{1,50}$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_specialization', message='Invalid specialization', regex="^[-!#$%&'*+./=?^_`{}|~A-Za-zА-яа-я-\\s]{1,250}$")], verbose_name='Teacher Specialization'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_surname', message='Invalid surname', regex='^[А-яа-я-\\s]{1,50}$')], verbose_name='Surname'),
        ),
    ]
