# Generated by Django 3.2.15 on 2022-09-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_availability_availabilityoccurrence_classroomreservation_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityoccurrence',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='availabilityoccurrence',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classroomreservation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='classroomreservation',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='padding_for',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='AvailabilityOccurrence',
        ),
        migrations.DeleteModel(
            name='ClassroomReservation',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
