# Generated by Django 3.2.15 on 2022-09-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20220907_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='subway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.subwaystation', verbose_name='Станции метро'),
        ),
    ]
